In [27]:
import boto3
from boto3.dynamodb.conditions import Key, Attr
import datetime

#session = boto3.Session(region_name='us-east-1',
#                        aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
#                        aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'])
#dynamodb = session.resource('dynamodb')
dynamodb = boto3.resource(service_name='dynamodb', region_name='us-east-1')

start_date = '20190101' #1641 2460???
table = dynamodb.Table('agencymbsfloating_prices')
response = table.scan(FilterExpression=Attr('Date').gt(start_date))
items = response['Items']

while response.get('LastEvaluatedKey', False):
    response = table.scan(
        FilterExpression=Attr('Date').gt(start_date),
        ExclusiveStartKey=response['LastEvaluatedKey'],
        Limit=10
    )
    items = items + response['Items']
print(len(items))

2460

In [30]:
import pandas as pd
import numpy as np

dfmbsfloating = pd.DataFrame(items)
dfmbsfloating.replace('*', '', inplace=True)
dfmbsfloating.replace('0', '', inplace=True)
dfmbsfloating.replace('0.0', '', inplace=True)
dfmbsfloating['Date'] = pd.to_datetime(dfmbsfloating['Date'], format='%Y%m%d')
dfmbsfloating
dfmbsfloating[dfmbsfloating.columns[0:5]] = dfmbsfloating[dfmbsfloating.columns[0:5]].apply(pd.to_numeric)
dfmbsfloating.replace(np.NaN, '', inplace=True)


temp = dfmbsfloating
temp = temp[temp['Measure'] == 'AVERAGE PRICE']
#temp = temp[temp.Agency == 'GNMA']
temp = temp[temp['Mortgage Type'] == 'ARMS/HYBRIDS']

temp = temp.set_index(['Date', 'Agency']).unstack(level=1)
temp = temp['3/1']
print(temp)

#blah = blah[blah['Mortgage Type'] == 'AVERAGE PRICE']
temp

Agency      FHLMC FNMA   GNMA
Date
2019-01-02
2019-01-03
2019-01-04
2019-01-07
2019-01-08
2019-01-09
2019-01-10
2019-01-11
2019-01-14
2019-01-15
2019-01-16
2019-01-17
2019-01-18               99.3
2019-01-22
2019-01-23
2019-01-24
2019-01-25
2019-01-28
2019-01-29
2019-01-30
2019-01-31
2019-02-01               99.6
2019-02-04               99.6
2019-02-05
2019-02-06
2019-02-07
2019-02-08
2019-02-11
2019-02-12               99.5
2019-02-13               99.1
...           ...  ...    ...
2019-03-19
2019-03-20               98.9
2019-03-21  103.7        99.6
2019-03-22
2019-03-25
2019-03-26
2019-03-27
2019-03-28
2019-03-29
2019-04-01
2019-04-02              100.2
2019-04-03
2019-04-04
2019-04-05
2019-04-08
2019-04-09
2019-04-10
2019-04-11
2019-04-12
2019-04-15
2019-04-16               99.5
2019-04-17
2019-04-18
2019-04-22
2019-04-23
2019-04-24
2019-04-25
2019-04-26
2019-04-29
2019-04-30              101.1

[82 rows x 3 columns]

Agency      FHLMC FNMA   GNMA
Date
2019-01-02
2019-01-03
2019-01-04
2019-01-07
2019-01-08
2019-01-09
2019-01-10
2019-01-11
2019-01-14
2019-01-15
2019-01-16
2019-01-17
2019-01-18               99.3
2019-01-22
2019-01-23
2019-01-24
2019-01-25
2019-01-28
2019-01-29
2019-01-30
2019-01-31
2019-02-01               99.6
2019-02-04               99.6
2019-02-05
2019-02-06
2019-02-07
2019-02-08
2019-02-11
2019-02-12               99.5
2019-02-13               99.1
...           ...  ...    ...
2019-03-19
2019-03-20               98.9
2019-03-21  103.7        99.6
2019-03-22
2019-03-25
2019-03-26
2019-03-27
2019-03-28
2019-03-29
2019-04-01
2019-04-02              100.2
2019-04-03
2019-04-04
2019-04-05
2019-04-08
2019-04-09
2019-04-10
2019-04-11
2019-04-12
2019-04-15
2019-04-16               99.5
2019-04-17
2019-04-18
2019-04-22
2019-04-23
2019-04-24
2019-04-25
2019-04-26
2019-04-29
2019-04-30              101.1

[82 rows x 3 columns]

In [31]:
def get_table_items(table_name, start_date):
    table = dynamodb.Table(table_name)
    response = table.scan(FilterExpression=Attr('Date').gt(start_date))
    items = response['Items']
    print(len(items))

    while response.get('LastEvaluatedKey', False):
        response = table.scan(
            FilterExpression=Attr('Date').gt(start_date),
            ExclusiveStartKey=response['LastEvaluatedKey'],
            Limit=10
        )
        print(len(items))
        items = items + response['Items']
 
    print(len(items))
    return items

dfmbsfloating = pd.DataFrame(get_table_items('agencymbsfloating_prices', '20190101'))

1641